User tinyproxy
Group tinyproxy
Port 8888
Listen 0.0.0.0
Timeout 600
LogFile "/tmp/tinyproxy.log"
LogLevel Info
PidFile "/run/tinyproxy.pid"
MaxClients 100
Allow 127.0.0.1
Allow ::1
Allow 10.0.0.0/8
Allow 172.16.0.0/12
Allow 192.168.0.0/16
Allow 100.64.0.0/10
ConnectPort 443
ConnectPort 80
